//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.22 at 11:20:53 AM BST 
//


package uk.ac.ed.inf.setmac.config.v1;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for engineBase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="engineBase">
 *   &lt;complexContent>
 *     &lt;restriction base="{urn://uk/ac/ed/inf/ace/config/v1}engineBase">
 *       &lt;sequence>
 *         &lt;element ref="{urn://uk/ac/ed/inf/ace/config/v1}databases"/>
 *         &lt;element ref="{urn://uk/ac/ed/inf/ace/config/v1}environments"/>
 *         &lt;element ref="{urn://uk/ac/ed/inf/ace/config/v1}dataSets"/>
 *         &lt;element ref="{urn://uk/ac/ed/inf/ace/config/v1}docTypes"/>
 *         &lt;element ref="{urn://uk/ac/ed/inf/ace/config/v1}classifiers"/>
 *         &lt;element ref="{urn://uk/ac/ed/inf/ace/config/v1}tasks"/>
 *         &lt;element ref="{urn://uk/ac/ed/inf/ace/config/v1}preCacheProcessors"/>
 *         &lt;element ref="{urn://uk/ac/ed/inf/ace/config/v1}postCacheProcessors"/>
 *         &lt;element ref="{urn://uk/ac/ed/inf/ace/config/v1}programmes"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" type="{urn://uk/ac/ed/inf/ace/config/v1}nonEmptyString" fixed="uk.ac.ed.inf.setmac.Engine" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "engineBase")
@XmlSeeAlso({
    Engine.class
})
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
public abstract class EngineBase
    extends uk.ac.ed.inf.ace.config.v1.EngineBase
{


}
