//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.22 at 11:20:53 AM BST 
//


package uk.ac.ed.inf.setmac.config.v1;

import java.math.BigDecimal;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{urn://uk/ac/ed/inf/setmac/config/v1}ldaBase">
 *       &lt;attribute name="alpha" type="{http://www.w3.org/2001/XMLSchema}decimal" default="50.0" />
 *       &lt;attribute name="beta" type="{http://www.w3.org/2001/XMLSchema}decimal" default="0.01" />
 *       &lt;attribute name="useSymmetricAlpha" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="numThreads" type="{urn://uk/ac/ed/inf/ace/config/v1}positiveNonZeroInt" default="1" />
 *       &lt;attribute name="printLogLikelihood" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="numEstimatorParticles" type="{urn://uk/ac/ed/inf/ace/config/v1}positiveNonZeroInt" default="10" />
 *       &lt;attribute name="estimatorUsingResampling" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="numInferencerIterations" type="{urn://uk/ac/ed/inf/ace/config/v1}positiveInt" default="100" />
 *       &lt;attribute name="inferencerThinning" type="{urn://uk/ac/ed/inf/ace/config/v1}positiveNonZeroInt" default="10" />
 *       &lt;attribute name="inferencerBurnIn" type="{urn://uk/ac/ed/inf/ace/config/v1}positiveNonZeroInt" default="10" />
 *       &lt;attribute name="instanceModelDistanceType" default="LeftToRight">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="None"/>
 *             &lt;enumeration value="LeftToRight"/>
 *             &lt;enumeration value="MeanTopics"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
public class Lda
    extends LdaBase
{

    @XmlAttribute(name = "alpha")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    protected BigDecimal alpha;
    @XmlAttribute(name = "beta")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    protected BigDecimal beta;
    @XmlAttribute(name = "useSymmetricAlpha")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    protected Boolean useSymmetricAlpha;
    @XmlAttribute(name = "numThreads")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    protected Integer numThreads;
    @XmlAttribute(name = "printLogLikelihood")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    protected Boolean printLogLikelihood;
    @XmlAttribute(name = "numEstimatorParticles")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    protected Integer numEstimatorParticles;
    @XmlAttribute(name = "estimatorUsingResampling")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    protected Boolean estimatorUsingResampling;
    @XmlAttribute(name = "numInferencerIterations")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    protected Integer numInferencerIterations;
    @XmlAttribute(name = "inferencerThinning")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    protected Integer inferencerThinning;
    @XmlAttribute(name = "inferencerBurnIn")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    protected Integer inferencerBurnIn;
    @XmlAttribute(name = "instanceModelDistanceType")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    protected String instanceModelDistanceType;

    /**
     * Gets the value of the alpha property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public BigDecimal getAlpha() {
        if (alpha == null) {
            return new BigDecimal("50.0");
        } else {
            return alpha;
        }
    }

    /**
     * Sets the value of the alpha property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public void setAlpha(BigDecimal value) {
        this.alpha = value;
    }

    /**
     * Gets the value of the beta property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public BigDecimal getBeta() {
        if (beta == null) {
            return new BigDecimal("0.01");
        } else {
            return beta;
        }
    }

    /**
     * Sets the value of the beta property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public void setBeta(BigDecimal value) {
        this.beta = value;
    }

    /**
     * Gets the value of the useSymmetricAlpha property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public boolean isUseSymmetricAlpha() {
        if (useSymmetricAlpha == null) {
            return false;
        } else {
            return useSymmetricAlpha;
        }
    }

    /**
     * Sets the value of the useSymmetricAlpha property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public void setUseSymmetricAlpha(Boolean value) {
        this.useSymmetricAlpha = value;
    }

    /**
     * Gets the value of the numThreads property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public int getNumThreads() {
        if (numThreads == null) {
            return  1;
        } else {
            return numThreads;
        }
    }

    /**
     * Sets the value of the numThreads property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public void setNumThreads(Integer value) {
        this.numThreads = value;
    }

    /**
     * Gets the value of the printLogLikelihood property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public boolean isPrintLogLikelihood() {
        if (printLogLikelihood == null) {
            return true;
        } else {
            return printLogLikelihood;
        }
    }

    /**
     * Sets the value of the printLogLikelihood property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public void setPrintLogLikelihood(Boolean value) {
        this.printLogLikelihood = value;
    }

    /**
     * Gets the value of the numEstimatorParticles property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public int getNumEstimatorParticles() {
        if (numEstimatorParticles == null) {
            return  10;
        } else {
            return numEstimatorParticles;
        }
    }

    /**
     * Sets the value of the numEstimatorParticles property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public void setNumEstimatorParticles(Integer value) {
        this.numEstimatorParticles = value;
    }

    /**
     * Gets the value of the estimatorUsingResampling property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public boolean isEstimatorUsingResampling() {
        if (estimatorUsingResampling == null) {
            return false;
        } else {
            return estimatorUsingResampling;
        }
    }

    /**
     * Sets the value of the estimatorUsingResampling property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public void setEstimatorUsingResampling(Boolean value) {
        this.estimatorUsingResampling = value;
    }

    /**
     * Gets the value of the numInferencerIterations property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public int getNumInferencerIterations() {
        if (numInferencerIterations == null) {
            return  100;
        } else {
            return numInferencerIterations;
        }
    }

    /**
     * Sets the value of the numInferencerIterations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public void setNumInferencerIterations(Integer value) {
        this.numInferencerIterations = value;
    }

    /**
     * Gets the value of the inferencerThinning property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public int getInferencerThinning() {
        if (inferencerThinning == null) {
            return  10;
        } else {
            return inferencerThinning;
        }
    }

    /**
     * Sets the value of the inferencerThinning property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public void setInferencerThinning(Integer value) {
        this.inferencerThinning = value;
    }

    /**
     * Gets the value of the inferencerBurnIn property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public int getInferencerBurnIn() {
        if (inferencerBurnIn == null) {
            return  10;
        } else {
            return inferencerBurnIn;
        }
    }

    /**
     * Sets the value of the inferencerBurnIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public void setInferencerBurnIn(Integer value) {
        this.inferencerBurnIn = value;
    }

    /**
     * Gets the value of the instanceModelDistanceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public String getInstanceModelDistanceType() {
        if (instanceModelDistanceType == null) {
            return "LeftToRight";
        } else {
            return instanceModelDistanceType;
        }
    }

    /**
     * Sets the value of the instanceModelDistanceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public void setInstanceModelDistanceType(String value) {
        this.instanceModelDistanceType = value;
    }

}
