//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.22 at 11:20:53 AM BST 
//


package uk.ac.ed.inf.setmac.config.v1;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import uk.ac.ed.inf.ace.config.v1.ClassifierBase;


/**
 * <p>Java class for malletClassifierBase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="malletClassifierBase">
 *   &lt;complexContent>
 *     &lt;extension base="{urn://uk/ac/ed/inf/ace/config/v1}classifierBase">
 *       &lt;attribute name="numTopics" type="{urn://uk/ac/ed/inf/ace/config/v1}positiveNonZeroInt" default="10" />
 *       &lt;attribute name="showTopicsInterval" type="{urn://uk/ac/ed/inf/ace/config/v1}positiveInt" default="0" />
 *       &lt;attribute name="topWords" type="{urn://uk/ac/ed/inf/ace/config/v1}positiveInt" default="20" />
 *       &lt;attribute name="numIterations" type="{urn://uk/ac/ed/inf/ace/config/v1}positiveNonZeroInt" default="1000" />
 *       &lt;attribute name="optimizeInterval" type="{urn://uk/ac/ed/inf/ace/config/v1}positiveInt" default="0" />
 *       &lt;attribute name="optimizeBurnIn" type="{urn://uk/ac/ed/inf/ace/config/v1}positiveInt" default="200" />
 *       &lt;attribute name="classifierType" default="MinimumDistance">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Svm"/>
 *             &lt;enumeration value="MinimumDistance"/>
 *             &lt;enumeration value="GaussianDistance"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "malletClassifierBase")
@XmlSeeAlso({
    SimpleLdaBase.class,
    DmrBase.class,
    LdaSvmBase.class,
    LdaBase.class
})
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
public abstract class MalletClassifierBase
    extends ClassifierBase
{

    @XmlAttribute(name = "numTopics")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    protected Integer numTopics;
    @XmlAttribute(name = "showTopicsInterval")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    protected Integer showTopicsInterval;
    @XmlAttribute(name = "topWords")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    protected Integer topWords;
    @XmlAttribute(name = "numIterations")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    protected Integer numIterations;
    @XmlAttribute(name = "optimizeInterval")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    protected Integer optimizeInterval;
    @XmlAttribute(name = "optimizeBurnIn")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    protected Integer optimizeBurnIn;
    @XmlAttribute(name = "classifierType")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    protected String classifierType;

    /**
     * Gets the value of the numTopics property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public int getNumTopics() {
        if (numTopics == null) {
            return  10;
        } else {
            return numTopics;
        }
    }

    /**
     * Sets the value of the numTopics property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public void setNumTopics(Integer value) {
        this.numTopics = value;
    }

    /**
     * Gets the value of the showTopicsInterval property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public int getShowTopicsInterval() {
        if (showTopicsInterval == null) {
            return  0;
        } else {
            return showTopicsInterval;
        }
    }

    /**
     * Sets the value of the showTopicsInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public void setShowTopicsInterval(Integer value) {
        this.showTopicsInterval = value;
    }

    /**
     * Gets the value of the topWords property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public int getTopWords() {
        if (topWords == null) {
            return  20;
        } else {
            return topWords;
        }
    }

    /**
     * Sets the value of the topWords property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public void setTopWords(Integer value) {
        this.topWords = value;
    }

    /**
     * Gets the value of the numIterations property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public int getNumIterations() {
        if (numIterations == null) {
            return  1000;
        } else {
            return numIterations;
        }
    }

    /**
     * Sets the value of the numIterations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public void setNumIterations(Integer value) {
        this.numIterations = value;
    }

    /**
     * Gets the value of the optimizeInterval property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public int getOptimizeInterval() {
        if (optimizeInterval == null) {
            return  0;
        } else {
            return optimizeInterval;
        }
    }

    /**
     * Sets the value of the optimizeInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public void setOptimizeInterval(Integer value) {
        this.optimizeInterval = value;
    }

    /**
     * Gets the value of the optimizeBurnIn property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public int getOptimizeBurnIn() {
        if (optimizeBurnIn == null) {
            return  200;
        } else {
            return optimizeBurnIn;
        }
    }

    /**
     * Sets the value of the optimizeBurnIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public void setOptimizeBurnIn(Integer value) {
        this.optimizeBurnIn = value;
    }

    /**
     * Gets the value of the classifierType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public String getClassifierType() {
        if (classifierType == null) {
            return "MinimumDistance";
        } else {
            return classifierType;
        }
    }

    /**
     * Sets the value of the classifierType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public void setClassifierType(String value) {
        this.classifierType = value;
    }

}
