//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.22 at 11:20:53 AM BST 
//


package uk.ac.ed.inf.setmac.config.v1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.ac.ed.inf.setmac.config.v1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _LdaSvm_QNAME = new QName("urn://uk/ac/ed/inf/setmac/config/v1", "ldaSvm");
    private final static QName _DataSet_QNAME = new QName("urn://uk/ac/ed/inf/setmac/config/v1", "dataSet");
    private final static QName _Dmr_QNAME = new QName("urn://uk/ac/ed/inf/setmac/config/v1", "dmr");
    private final static QName _Flagged_QNAME = new QName("urn://uk/ac/ed/inf/setmac/config/v1", "flagged");
    private final static QName _Lda_QNAME = new QName("urn://uk/ac/ed/inf/setmac/config/v1", "lda");
    private final static QName _SqliteDatabase_QNAME = new QName("urn://uk/ac/ed/inf/setmac/config/v1", "sqliteDatabase");
    private final static QName _SimpleLda_QNAME = new QName("urn://uk/ac/ed/inf/setmac/config/v1", "simpleLda");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.ac.ed.inf.setmac.config.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Engine }
     * 
     */
    public Engine createEngine() {
        return new Engine();
    }

    /**
     * Create an instance of {@link SimpleLda }
     * 
     */
    public SimpleLda createSimpleLda() {
        return new SimpleLda();
    }

    /**
     * Create an instance of {@link SqliteDatabase }
     * 
     */
    public SqliteDatabase createSqliteDatabase() {
        return new SqliteDatabase();
    }

    /**
     * Create an instance of {@link Engine.Sites }
     * 
     */
    public Engine.Sites createEngineSites() {
        return new Engine.Sites();
    }

    /**
     * Create an instance of {@link Flagged }
     * 
     */
    public Flagged createFlagged() {
        return new Flagged();
    }

    /**
     * Create an instance of {@link Dmr }
     * 
     */
    public Dmr createDmr() {
        return new Dmr();
    }

    /**
     * Create an instance of {@link LdaSvm }
     * 
     */
    public LdaSvm createLdaSvm() {
        return new LdaSvm();
    }

    /**
     * Create an instance of {@link Lda }
     * 
     */
    public Lda createLda() {
        return new Lda();
    }

    /**
     * Create an instance of {@link DataSet }
     * 
     */
    public DataSet createDataSet() {
        return new DataSet();
    }

    /**
     * Create an instance of {@link Site }
     * 
     */
    public Site createSite() {
        return new Site();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LdaSvm }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn://uk/ac/ed/inf/setmac/config/v1", name = "ldaSvm", substitutionHeadNamespace = "urn://uk/ac/ed/inf/ace/config/v1", substitutionHeadName = "classifierBase")
    public JAXBElement<LdaSvm> createLdaSvm(LdaSvm value) {
        return new JAXBElement<LdaSvm>(_LdaSvm_QNAME, LdaSvm.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataSet }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn://uk/ac/ed/inf/setmac/config/v1", name = "dataSet", substitutionHeadNamespace = "urn://uk/ac/ed/inf/ace/config/v1", substitutionHeadName = "dataSetBase")
    public JAXBElement<DataSet> createDataSet(DataSet value) {
        return new JAXBElement<DataSet>(_DataSet_QNAME, DataSet.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Dmr }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn://uk/ac/ed/inf/setmac/config/v1", name = "dmr", substitutionHeadNamespace = "urn://uk/ac/ed/inf/ace/config/v1", substitutionHeadName = "classifierBase")
    public JAXBElement<Dmr> createDmr(Dmr value) {
        return new JAXBElement<Dmr>(_Dmr_QNAME, Dmr.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Flagged }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn://uk/ac/ed/inf/setmac/config/v1", name = "flagged", substitutionHeadNamespace = "urn://uk/ac/ed/inf/ace/config/v1", substitutionHeadName = "docTypeBase")
    public JAXBElement<Flagged> createFlagged(Flagged value) {
        return new JAXBElement<Flagged>(_Flagged_QNAME, Flagged.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Lda }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn://uk/ac/ed/inf/setmac/config/v1", name = "lda", substitutionHeadNamespace = "urn://uk/ac/ed/inf/ace/config/v1", substitutionHeadName = "classifierBase")
    public JAXBElement<Lda> createLda(Lda value) {
        return new JAXBElement<Lda>(_Lda_QNAME, Lda.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SqliteDatabase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn://uk/ac/ed/inf/setmac/config/v1", name = "sqliteDatabase", substitutionHeadNamespace = "urn://uk/ac/ed/inf/ace/config/v1", substitutionHeadName = "databaseBase")
    public JAXBElement<SqliteDatabase> createSqliteDatabase(SqliteDatabase value) {
        return new JAXBElement<SqliteDatabase>(_SqliteDatabase_QNAME, SqliteDatabase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleLda }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn://uk/ac/ed/inf/setmac/config/v1", name = "simpleLda", substitutionHeadNamespace = "urn://uk/ac/ed/inf/ace/config/v1", substitutionHeadName = "classifierBase")
    public JAXBElement<SimpleLda> createSimpleLda(SimpleLda value) {
        return new JAXBElement<SimpleLda>(_SimpleLda_QNAME, SimpleLda.class, null, value);
    }

}
