//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.22 at 11:20:53 AM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn://uk/ac/ed/inf/setmac/config/v1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package uk.ac.ed.inf.setmac.config.v1;
