//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.22 at 11:20:53 AM BST 
//


package uk.ac.ed.inf.setmac.config.v1;

import java.math.BigDecimal;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{urn://uk/ac/ed/inf/setmac/config/v1}simpleLdaBase">
 *       &lt;attribute name="alpha" type="{http://www.w3.org/2001/XMLSchema}decimal" default="50.0" />
 *       &lt;attribute name="beta" type="{http://www.w3.org/2001/XMLSchema}decimal" default="0.01" />
 *       &lt;attribute name="numInferencerIterations" type="{urn://uk/ac/ed/inf/ace/config/v1}positiveInt" default="100" />
 *       &lt;attribute name="inferencerThinning" type="{urn://uk/ac/ed/inf/ace/config/v1}positiveNonZeroInt" default="10" />
 *       &lt;attribute name="inferencerBurnIn" type="{urn://uk/ac/ed/inf/ace/config/v1}positiveNonZeroInt" default="10" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
public class SimpleLda
    extends SimpleLdaBase
{

    @XmlAttribute(name = "alpha")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    protected BigDecimal alpha;
    @XmlAttribute(name = "beta")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    protected BigDecimal beta;
    @XmlAttribute(name = "numInferencerIterations")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    protected Integer numInferencerIterations;
    @XmlAttribute(name = "inferencerThinning")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    protected Integer inferencerThinning;
    @XmlAttribute(name = "inferencerBurnIn")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    protected Integer inferencerBurnIn;

    /**
     * Gets the value of the alpha property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public BigDecimal getAlpha() {
        if (alpha == null) {
            return new BigDecimal("50.0");
        } else {
            return alpha;
        }
    }

    /**
     * Sets the value of the alpha property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public void setAlpha(BigDecimal value) {
        this.alpha = value;
    }

    /**
     * Gets the value of the beta property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public BigDecimal getBeta() {
        if (beta == null) {
            return new BigDecimal("0.01");
        } else {
            return beta;
        }
    }

    /**
     * Sets the value of the beta property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public void setBeta(BigDecimal value) {
        this.beta = value;
    }

    /**
     * Gets the value of the numInferencerIterations property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public int getNumInferencerIterations() {
        if (numInferencerIterations == null) {
            return  100;
        } else {
            return numInferencerIterations;
        }
    }

    /**
     * Sets the value of the numInferencerIterations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public void setNumInferencerIterations(Integer value) {
        this.numInferencerIterations = value;
    }

    /**
     * Gets the value of the inferencerThinning property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public int getInferencerThinning() {
        if (inferencerThinning == null) {
            return  10;
        } else {
            return inferencerThinning;
        }
    }

    /**
     * Sets the value of the inferencerThinning property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public void setInferencerThinning(Integer value) {
        this.inferencerThinning = value;
    }

    /**
     * Gets the value of the inferencerBurnIn property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public int getInferencerBurnIn() {
        if (inferencerBurnIn == null) {
            return  10;
        } else {
            return inferencerBurnIn;
        }
    }

    /**
     * Sets the value of the inferencerBurnIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:53+01:00", comments = "JAXB RI v2.2.4-2")
    public void setInferencerBurnIn(Integer value) {
        this.inferencerBurnIn = value;
    }

}
