//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.22 at 11:20:52 AM BST 
//


package uk.ac.ed.inf.ace.config.v1;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for engineBase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="engineBase">
 *   &lt;complexContent>
 *     &lt;extension base="{urn://uk/ac/ed/inf/ace/config/v1}typeable">
 *       &lt;sequence>
 *         &lt;element ref="{urn://uk/ac/ed/inf/ace/config/v1}databases"/>
 *         &lt;element ref="{urn://uk/ac/ed/inf/ace/config/v1}environments"/>
 *         &lt;element ref="{urn://uk/ac/ed/inf/ace/config/v1}dataSets"/>
 *         &lt;element ref="{urn://uk/ac/ed/inf/ace/config/v1}docTypes"/>
 *         &lt;element ref="{urn://uk/ac/ed/inf/ace/config/v1}classifiers"/>
 *         &lt;element ref="{urn://uk/ac/ed/inf/ace/config/v1}tasks"/>
 *         &lt;element ref="{urn://uk/ac/ed/inf/ace/config/v1}preCacheProcessors"/>
 *         &lt;element ref="{urn://uk/ac/ed/inf/ace/config/v1}postCacheProcessors"/>
 *         &lt;element ref="{urn://uk/ac/ed/inf/ace/config/v1}programmes"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "engineBase", propOrder = {
    "databases",
    "environments",
    "dataSets",
    "docTypes",
    "classifiers",
    "tasks",
    "preCacheProcessors",
    "postCacheProcessors",
    "programmes"
})
@XmlSeeAlso({
    Engine.class
})
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
public abstract class EngineBase
    extends Typeable
{

    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    protected Databases databases;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    protected Environments environments;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    protected DataSets dataSets;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    protected DocTypes docTypes;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    protected Classifiers classifiers;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    protected Tasks tasks;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    protected PreCacheProcessors preCacheProcessors;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    protected PostCacheProcessors postCacheProcessors;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    protected Programmes programmes;

    /**
     * Gets the value of the databases property.
     * 
     * @return
     *     possible object is
     *     {@link Databases }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public Databases getDatabases() {
        return databases;
    }

    /**
     * Sets the value of the databases property.
     * 
     * @param value
     *     allowed object is
     *     {@link Databases }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public void setDatabases(Databases value) {
        this.databases = value;
    }

    /**
     * Gets the value of the environments property.
     * 
     * @return
     *     possible object is
     *     {@link Environments }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public Environments getEnvironments() {
        return environments;
    }

    /**
     * Sets the value of the environments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Environments }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public void setEnvironments(Environments value) {
        this.environments = value;
    }

    /**
     * Gets the value of the dataSets property.
     * 
     * @return
     *     possible object is
     *     {@link DataSets }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public DataSets getDataSets() {
        return dataSets;
    }

    /**
     * Sets the value of the dataSets property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSets }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public void setDataSets(DataSets value) {
        this.dataSets = value;
    }

    /**
     * Gets the value of the docTypes property.
     * 
     * @return
     *     possible object is
     *     {@link DocTypes }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public DocTypes getDocTypes() {
        return docTypes;
    }

    /**
     * Sets the value of the docTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocTypes }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public void setDocTypes(DocTypes value) {
        this.docTypes = value;
    }

    /**
     * Gets the value of the classifiers property.
     * 
     * @return
     *     possible object is
     *     {@link Classifiers }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public Classifiers getClassifiers() {
        return classifiers;
    }

    /**
     * Sets the value of the classifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Classifiers }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public void setClassifiers(Classifiers value) {
        this.classifiers = value;
    }

    /**
     * Gets the value of the tasks property.
     * 
     * @return
     *     possible object is
     *     {@link Tasks }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public Tasks getTasks() {
        return tasks;
    }

    /**
     * Sets the value of the tasks property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tasks }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public void setTasks(Tasks value) {
        this.tasks = value;
    }

    /**
     * Gets the value of the preCacheProcessors property.
     * 
     * @return
     *     possible object is
     *     {@link PreCacheProcessors }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public PreCacheProcessors getPreCacheProcessors() {
        return preCacheProcessors;
    }

    /**
     * Sets the value of the preCacheProcessors property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreCacheProcessors }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public void setPreCacheProcessors(PreCacheProcessors value) {
        this.preCacheProcessors = value;
    }

    /**
     * Gets the value of the postCacheProcessors property.
     * 
     * @return
     *     possible object is
     *     {@link PostCacheProcessors }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public PostCacheProcessors getPostCacheProcessors() {
        return postCacheProcessors;
    }

    /**
     * Sets the value of the postCacheProcessors property.
     * 
     * @param value
     *     allowed object is
     *     {@link PostCacheProcessors }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public void setPostCacheProcessors(PostCacheProcessors value) {
        this.postCacheProcessors = value;
    }

    /**
     * Gets the value of the programmes property.
     * 
     * @return
     *     possible object is
     *     {@link Programmes }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public Programmes getProgrammes() {
        return programmes;
    }

    /**
     * Sets the value of the programmes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Programmes }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public void setProgrammes(Programmes value) {
        this.programmes = value;
    }

}
