//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.22 at 11:20:52 AM BST 
//


package uk.ac.ed.inf.ace.config.v1;

import java.math.BigDecimal;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for environment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="environment">
 *   &lt;complexContent>
 *     &lt;extension base="{urn://uk/ac/ed/inf/ace/config/v1}named">
 *       &lt;attribute name="randomSeed" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="holdOutProportion" use="required" type="{urn://uk/ac/ed/inf/ace/config/v1}proportion" />
 *       &lt;attribute name="database" use="required" type="{urn://uk/ac/ed/inf/ace/config/v1}nonEmptyString" />
 *       &lt;attribute name="outputPath" use="required" type="{urn://uk/ac/ed/inf/ace/config/v1}nonEmptyString" />
 *       &lt;attribute name="threadPoolSize" use="required" type="{urn://uk/ac/ed/inf/ace/config/v1}positiveNonZeroInt" />
 *       &lt;attribute name="crossValidationFolds" use="required" type="{urn://uk/ac/ed/inf/ace/config/v1}positiveNonZeroInt" />
 *       &lt;attribute name="classificationDocType" use="required" type="{urn://uk/ac/ed/inf/ace/config/v1}nonEmptyString" />
 *       &lt;attribute name="sampleProbability" type="{urn://uk/ac/ed/inf/ace/config/v1}proportion" default="1.0" />
 *       &lt;attribute name="cacheCapacity" use="required" type="{urn://uk/ac/ed/inf/ace/config/v1}positiveInt" />
 *       &lt;attribute name="cacheEvictAfterAccess" use="required" type="{urn://uk/ac/ed/inf/ace/config/v1}positiveInt" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "environment")
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
public class Environment
    extends Named
{

    @XmlAttribute(name = "randomSeed", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    protected long randomSeed;
    @XmlAttribute(name = "holdOutProportion", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    protected BigDecimal holdOutProportion;
    @XmlAttribute(name = "database", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    protected String database;
    @XmlAttribute(name = "outputPath", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    protected String outputPath;
    @XmlAttribute(name = "threadPoolSize", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    protected int threadPoolSize;
    @XmlAttribute(name = "crossValidationFolds", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    protected int crossValidationFolds;
    @XmlAttribute(name = "classificationDocType", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    protected String classificationDocType;
    @XmlAttribute(name = "sampleProbability")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    protected BigDecimal sampleProbability;
    @XmlAttribute(name = "cacheCapacity", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    protected int cacheCapacity;
    @XmlAttribute(name = "cacheEvictAfterAccess", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    protected int cacheEvictAfterAccess;

    /**
     * Gets the value of the randomSeed property.
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public long getRandomSeed() {
        return randomSeed;
    }

    /**
     * Sets the value of the randomSeed property.
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public void setRandomSeed(long value) {
        this.randomSeed = value;
    }

    /**
     * Gets the value of the holdOutProportion property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public BigDecimal getHoldOutProportion() {
        return holdOutProportion;
    }

    /**
     * Sets the value of the holdOutProportion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public void setHoldOutProportion(BigDecimal value) {
        this.holdOutProportion = value;
    }

    /**
     * Gets the value of the database property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public String getDatabase() {
        return database;
    }

    /**
     * Sets the value of the database property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public void setDatabase(String value) {
        this.database = value;
    }

    /**
     * Gets the value of the outputPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public String getOutputPath() {
        return outputPath;
    }

    /**
     * Sets the value of the outputPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public void setOutputPath(String value) {
        this.outputPath = value;
    }

    /**
     * Gets the value of the threadPoolSize property.
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public int getThreadPoolSize() {
        return threadPoolSize;
    }

    /**
     * Sets the value of the threadPoolSize property.
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public void setThreadPoolSize(int value) {
        this.threadPoolSize = value;
    }

    /**
     * Gets the value of the crossValidationFolds property.
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public int getCrossValidationFolds() {
        return crossValidationFolds;
    }

    /**
     * Sets the value of the crossValidationFolds property.
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public void setCrossValidationFolds(int value) {
        this.crossValidationFolds = value;
    }

    /**
     * Gets the value of the classificationDocType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public String getClassificationDocType() {
        return classificationDocType;
    }

    /**
     * Sets the value of the classificationDocType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public void setClassificationDocType(String value) {
        this.classificationDocType = value;
    }

    /**
     * Gets the value of the sampleProbability property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public BigDecimal getSampleProbability() {
        if (sampleProbability == null) {
            return new BigDecimal("1.0");
        } else {
            return sampleProbability;
        }
    }

    /**
     * Sets the value of the sampleProbability property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public void setSampleProbability(BigDecimal value) {
        this.sampleProbability = value;
    }

    /**
     * Gets the value of the cacheCapacity property.
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public int getCacheCapacity() {
        return cacheCapacity;
    }

    /**
     * Sets the value of the cacheCapacity property.
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public void setCacheCapacity(int value) {
        this.cacheCapacity = value;
    }

    /**
     * Gets the value of the cacheEvictAfterAccess property.
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public int getCacheEvictAfterAccess() {
        return cacheEvictAfterAccess;
    }

    /**
     * Sets the value of the cacheEvictAfterAccess property.
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public void setCacheEvictAfterAccess(int value) {
        this.cacheEvictAfterAccess = value;
    }

}
