//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.22 at 11:20:52 AM BST 
//


package uk.ac.ed.inf.ace.config.v1;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for programme complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="programme">
 *   &lt;complexContent>
 *     &lt;extension base="{urn://uk/ac/ed/inf/ace/config/v1}enableable">
 *       &lt;sequence>
 *         &lt;element name="dataSets" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element ref="{urn://uk/ac/ed/inf/ace/config/v1}dataSetBase"/>
 *                   &lt;element name="dataSetRef" type="{urn://uk/ac/ed/inf/ace/config/v1}reference"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="docTypes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element ref="{urn://uk/ac/ed/inf/ace/config/v1}docTypeBase"/>
 *                   &lt;element name="docTypeRef" type="{urn://uk/ac/ed/inf/ace/config/v1}reference"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="classifiers" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element ref="{urn://uk/ac/ed/inf/ace/config/v1}classifierBase"/>
 *                   &lt;element name="classifierRef" type="{urn://uk/ac/ed/inf/ace/config/v1}reference"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="tasks" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element ref="{urn://uk/ac/ed/inf/ace/config/v1}taskBase"/>
 *                   &lt;element name="taskRef" type="{urn://uk/ac/ed/inf/ace/config/v1}reference"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="preCacheProcessors" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element ref="{urn://uk/ac/ed/inf/ace/config/v1}processorBase"/>
 *                   &lt;element name="processorRef" type="{urn://uk/ac/ed/inf/ace/config/v1}reference"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="postCacheProcessors" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element ref="{urn://uk/ac/ed/inf/ace/config/v1}processorBase"/>
 *                   &lt;element name="processorRef" type="{urn://uk/ac/ed/inf/ace/config/v1}reference"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="randomSeed" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="crossValidationFolds" type="{urn://uk/ac/ed/inf/ace/config/v1}positiveNonZeroInt" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "programme", propOrder = {
    "dataSets",
    "docTypes",
    "classifiers",
    "tasks",
    "preCacheProcessors",
    "postCacheProcessors"
})
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
public class Programme
    extends Enableable
{

    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    protected Programme.DataSets dataSets;
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    protected Programme.DocTypes docTypes;
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    protected Programme.Classifiers classifiers;
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    protected Programme.Tasks tasks;
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    protected Programme.PreCacheProcessors preCacheProcessors;
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    protected Programme.PostCacheProcessors postCacheProcessors;
    @XmlAttribute(name = "randomSeed")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    protected Long randomSeed;
    @XmlAttribute(name = "crossValidationFolds")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    protected Integer crossValidationFolds;

    /**
     * Gets the value of the dataSets property.
     * 
     * @return
     *     possible object is
     *     {@link Programme.DataSets }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public Programme.DataSets getDataSets() {
        return dataSets;
    }

    /**
     * Sets the value of the dataSets property.
     * 
     * @param value
     *     allowed object is
     *     {@link Programme.DataSets }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public void setDataSets(Programme.DataSets value) {
        this.dataSets = value;
    }

    /**
     * Gets the value of the docTypes property.
     * 
     * @return
     *     possible object is
     *     {@link Programme.DocTypes }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public Programme.DocTypes getDocTypes() {
        return docTypes;
    }

    /**
     * Sets the value of the docTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Programme.DocTypes }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public void setDocTypes(Programme.DocTypes value) {
        this.docTypes = value;
    }

    /**
     * Gets the value of the classifiers property.
     * 
     * @return
     *     possible object is
     *     {@link Programme.Classifiers }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public Programme.Classifiers getClassifiers() {
        return classifiers;
    }

    /**
     * Sets the value of the classifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Programme.Classifiers }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public void setClassifiers(Programme.Classifiers value) {
        this.classifiers = value;
    }

    /**
     * Gets the value of the tasks property.
     * 
     * @return
     *     possible object is
     *     {@link Programme.Tasks }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public Programme.Tasks getTasks() {
        return tasks;
    }

    /**
     * Sets the value of the tasks property.
     * 
     * @param value
     *     allowed object is
     *     {@link Programme.Tasks }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public void setTasks(Programme.Tasks value) {
        this.tasks = value;
    }

    /**
     * Gets the value of the preCacheProcessors property.
     * 
     * @return
     *     possible object is
     *     {@link Programme.PreCacheProcessors }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public Programme.PreCacheProcessors getPreCacheProcessors() {
        return preCacheProcessors;
    }

    /**
     * Sets the value of the preCacheProcessors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Programme.PreCacheProcessors }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public void setPreCacheProcessors(Programme.PreCacheProcessors value) {
        this.preCacheProcessors = value;
    }

    /**
     * Gets the value of the postCacheProcessors property.
     * 
     * @return
     *     possible object is
     *     {@link Programme.PostCacheProcessors }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public Programme.PostCacheProcessors getPostCacheProcessors() {
        return postCacheProcessors;
    }

    /**
     * Sets the value of the postCacheProcessors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Programme.PostCacheProcessors }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public void setPostCacheProcessors(Programme.PostCacheProcessors value) {
        this.postCacheProcessors = value;
    }

    /**
     * Gets the value of the randomSeed property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public Long getRandomSeed() {
        return randomSeed;
    }

    /**
     * Sets the value of the randomSeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public void setRandomSeed(Long value) {
        this.randomSeed = value;
    }

    /**
     * Gets the value of the crossValidationFolds property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public Integer getCrossValidationFolds() {
        return crossValidationFolds;
    }

    /**
     * Sets the value of the crossValidationFolds property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public void setCrossValidationFolds(Integer value) {
        this.crossValidationFolds = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded" minOccurs="0">
     *         &lt;element ref="{urn://uk/ac/ed/inf/ace/config/v1}classifierBase"/>
     *         &lt;element name="classifierRef" type="{urn://uk/ac/ed/inf/ace/config/v1}reference"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "classifierBaseOrClassifierRef"
    })
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public static class Classifiers {

        @XmlElementRefs({
            @XmlElementRef(name = "classifierRef", namespace = "urn://uk/ac/ed/inf/ace/config/v1", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "classifierBase", namespace = "urn://uk/ac/ed/inf/ace/config/v1", type = JAXBElement.class, required = false)
        })
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
        protected List<JAXBElement<? extends Enableable>> classifierBaseOrClassifierRef;

        /**
         * Gets the value of the classifierBaseOrClassifierRef property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the classifierBaseOrClassifierRef property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getClassifierBaseOrClassifierRef().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link WekaClassifier }{@code >}
         * {@link JAXBElement }{@code <}{@link Classifier }{@code >}
         * {@link JAXBElement }{@code <}{@link Reference }{@code >}
         * {@link JAXBElement }{@code <}{@link ClassifierBase }{@code >}
         * 
         * 
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
        public List<JAXBElement<? extends Enableable>> getClassifierBaseOrClassifierRef() {
            if (classifierBaseOrClassifierRef == null) {
                classifierBaseOrClassifierRef = new ArrayList<JAXBElement<? extends Enableable>>();
            }
            return this.classifierBaseOrClassifierRef;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded" minOccurs="0">
     *         &lt;element ref="{urn://uk/ac/ed/inf/ace/config/v1}dataSetBase"/>
     *         &lt;element name="dataSetRef" type="{urn://uk/ac/ed/inf/ace/config/v1}reference"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dataSetBaseOrDataSetRef"
    })
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public static class DataSets {

        @XmlElementRefs({
            @XmlElementRef(name = "dataSetRef", namespace = "urn://uk/ac/ed/inf/ace/config/v1", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "dataSetBase", namespace = "urn://uk/ac/ed/inf/ace/config/v1", type = JAXBElement.class, required = false)
        })
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
        protected List<JAXBElement<? extends Enableable>> dataSetBaseOrDataSetRef;

        /**
         * Gets the value of the dataSetBaseOrDataSetRef property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dataSetBaseOrDataSetRef property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDataSetBaseOrDataSetRef().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link DataSet }{@code >}
         * {@link JAXBElement }{@code <}{@link Reference }{@code >}
         * {@link JAXBElement }{@code <}{@link DataSetBase }{@code >}
         * 
         * 
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
        public List<JAXBElement<? extends Enableable>> getDataSetBaseOrDataSetRef() {
            if (dataSetBaseOrDataSetRef == null) {
                dataSetBaseOrDataSetRef = new ArrayList<JAXBElement<? extends Enableable>>();
            }
            return this.dataSetBaseOrDataSetRef;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded" minOccurs="0">
     *         &lt;element ref="{urn://uk/ac/ed/inf/ace/config/v1}docTypeBase"/>
     *         &lt;element name="docTypeRef" type="{urn://uk/ac/ed/inf/ace/config/v1}reference"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "docTypeBaseOrDocTypeRef"
    })
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public static class DocTypes {

        @XmlElementRefs({
            @XmlElementRef(name = "docTypeBase", namespace = "urn://uk/ac/ed/inf/ace/config/v1", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "docTypeRef", namespace = "urn://uk/ac/ed/inf/ace/config/v1", type = JAXBElement.class, required = false)
        })
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
        protected List<JAXBElement<? extends Enableable>> docTypeBaseOrDocTypeRef;

        /**
         * Gets the value of the docTypeBaseOrDocTypeRef property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the docTypeBaseOrDocTypeRef property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDocTypeBaseOrDocTypeRef().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link Reference }{@code >}
         * {@link JAXBElement }{@code <}{@link DocTypeBase }{@code >}
         * {@link JAXBElement }{@code <}{@link DocType }{@code >}
         * 
         * 
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
        public List<JAXBElement<? extends Enableable>> getDocTypeBaseOrDocTypeRef() {
            if (docTypeBaseOrDocTypeRef == null) {
                docTypeBaseOrDocTypeRef = new ArrayList<JAXBElement<? extends Enableable>>();
            }
            return this.docTypeBaseOrDocTypeRef;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded" minOccurs="0">
     *         &lt;element ref="{urn://uk/ac/ed/inf/ace/config/v1}processorBase"/>
     *         &lt;element name="processorRef" type="{urn://uk/ac/ed/inf/ace/config/v1}reference"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "processorBaseOrProcessorRef"
    })
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public static class PostCacheProcessors {

        @XmlElementRefs({
            @XmlElementRef(name = "processorRef", namespace = "urn://uk/ac/ed/inf/ace/config/v1", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "processorBase", namespace = "urn://uk/ac/ed/inf/ace/config/v1", type = JAXBElement.class, required = false)
        })
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
        protected List<JAXBElement<? extends Enableable>> processorBaseOrProcessorRef;

        /**
         * Gets the value of the processorBaseOrProcessorRef property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the processorBaseOrProcessorRef property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProcessorBaseOrProcessorRef().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link RemoveStopwords }{@code >}
         * {@link JAXBElement }{@code <}{@link FilterByLabel }{@code >}
         * {@link JAXBElement }{@code <}{@link Processor }{@code >}
         * {@link JAXBElement }{@code <}{@link Tokenizer }{@code >}
         * {@link JAXBElement }{@code <}{@link ProcessorBase }{@code >}
         * {@link JAXBElement }{@code <}{@link Reference }{@code >}
         * 
         * 
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
        public List<JAXBElement<? extends Enableable>> getProcessorBaseOrProcessorRef() {
            if (processorBaseOrProcessorRef == null) {
                processorBaseOrProcessorRef = new ArrayList<JAXBElement<? extends Enableable>>();
            }
            return this.processorBaseOrProcessorRef;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded" minOccurs="0">
     *         &lt;element ref="{urn://uk/ac/ed/inf/ace/config/v1}processorBase"/>
     *         &lt;element name="processorRef" type="{urn://uk/ac/ed/inf/ace/config/v1}reference"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "processorBaseOrProcessorRef"
    })
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public static class PreCacheProcessors {

        @XmlElementRefs({
            @XmlElementRef(name = "processorBase", namespace = "urn://uk/ac/ed/inf/ace/config/v1", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "processorRef", namespace = "urn://uk/ac/ed/inf/ace/config/v1", type = JAXBElement.class, required = false)
        })
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
        protected List<JAXBElement<? extends Enableable>> processorBaseOrProcessorRef;

        /**
         * Gets the value of the processorBaseOrProcessorRef property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the processorBaseOrProcessorRef property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProcessorBaseOrProcessorRef().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link FilterByLabel }{@code >}
         * {@link JAXBElement }{@code <}{@link RemoveStopwords }{@code >}
         * {@link JAXBElement }{@code <}{@link Processor }{@code >}
         * {@link JAXBElement }{@code <}{@link Reference }{@code >}
         * {@link JAXBElement }{@code <}{@link Tokenizer }{@code >}
         * {@link JAXBElement }{@code <}{@link ProcessorBase }{@code >}
         * 
         * 
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
        public List<JAXBElement<? extends Enableable>> getProcessorBaseOrProcessorRef() {
            if (processorBaseOrProcessorRef == null) {
                processorBaseOrProcessorRef = new ArrayList<JAXBElement<? extends Enableable>>();
            }
            return this.processorBaseOrProcessorRef;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded" minOccurs="0">
     *         &lt;element ref="{urn://uk/ac/ed/inf/ace/config/v1}taskBase"/>
     *         &lt;element name="taskRef" type="{urn://uk/ac/ed/inf/ace/config/v1}reference"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "taskBaseOrTaskRef"
    })
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
    public static class Tasks {

        @XmlElementRefs({
            @XmlElementRef(name = "taskBase", namespace = "urn://uk/ac/ed/inf/ace/config/v1", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "taskRef", namespace = "urn://uk/ac/ed/inf/ace/config/v1", type = JAXBElement.class, required = false)
        })
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
        protected List<JAXBElement<? extends Enableable>> taskBaseOrTaskRef;

        /**
         * Gets the value of the taskBaseOrTaskRef property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the taskBaseOrTaskRef property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTaskBaseOrTaskRef().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link MultiClassTask }{@code >}
         * {@link JAXBElement }{@code <}{@link BinaryTask }{@code >}
         * {@link JAXBElement }{@code <}{@link TaskBase }{@code >}
         * {@link JAXBElement }{@code <}{@link BinaryIntegerTask }{@code >}
         * {@link JAXBElement }{@code <}{@link Task }{@code >}
         * {@link JAXBElement }{@code <}{@link Reference }{@code >}
         * {@link JAXBElement }{@code <}{@link MultiClassIntegerTask }{@code >}
         * 
         * 
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-09-22T11:20:52+01:00", comments = "JAXB RI v2.2.4-2")
        public List<JAXBElement<? extends Enableable>> getTaskBaseOrTaskRef() {
            if (taskBaseOrTaskRef == null) {
                taskBaseOrTaskRef = new ArrayList<JAXBElement<? extends Enableable>>();
            }
            return this.taskBaseOrTaskRef;
        }

    }

}
